/**
 * Story Format Templates
 *
 * Pre-built narrative structures for founders.
 * Each template embodies a specific communication purpose.
 * Opinionated, disciplined, ready to use.
 */

import { EmailTemplate, SectionContent } from './types/email';

export interface TemplatePreset {
  id: string;
  name: string;
  description: string;
  category: 'founder' | 'product' | 'update' | 'outreach';
  sections: SectionContent[];
}

export const TEMPLATE_PRESETS: TemplatePreset[] = [
  {
    id: 'investor-update',
    name: 'Investor Update',
    description: 'Monthly update for investors. Executive summary, metrics, roadmap, asks.',
    category: 'founder',
    sections: [
      {
        id: crypto.randomUUID(),
        type: 'heading',
        text: 'Monthly Update — November 2025',
        size: '3xl',
        align: 'left',
        weight: 600,
        spacing: { top: 1, bottom: 6 },
      },
      {
        id: crypto.randomUUID(),
        type: 'subheading',
        text: 'Executive Summary',
        size: 'xl',
        align: 'left',
        weight: 600,
        spacing: { top: 7, bottom: 4 },
      },
      {
        id: crypto.randomUUID(),
        type: 'text',
        text: 'This month we achieved three critical milestones that position us strongly for our Series A. Revenue grew 40% month-over-month, we launched our enterprise tier, and signed our first Fortune 500 customer.',
        size: 'base',
        align: 'left',
        lineHeight: 'relaxed',
        spacing: { top: 1, bottom: 6 },
      },
      {
        id: crypto.randomUUID(),
        type: 'subheading',
        text: 'Key Metrics',
        size: 'xl',
        align: 'left',
        weight: 600,
        spacing: { top: 7, bottom: 4 },
      },
      {
        id: crypto.randomUUID(),
        type: 'text',
        text: 'MRR: $127K (+40% MoM)\nCustomers: 89 (+23 new)\nChurn: 2.1% (target: <3%)\nCAC Payback: 8 months',
        size: 'base',
        align: 'left',
        lineHeight: 'loose',
        spacing: { top: 1, bottom: 6 },
      },
      {
        id: crypto.randomUUID(),
        type: 'subheading',
        text: 'What\'s Next',
        size: 'xl',
        align: 'left',
        weight: 600,
        spacing: { top: 7, bottom: 4 },
      },
      {
        id: crypto.randomUUID(),
        type: 'text',
        text: 'We\'re focused on three priorities: closing 5 more enterprise deals by year-end, launching our API platform, and hiring a VP of Sales. Timeline: 60 days.',
        size: 'base',
        align: 'left',
        lineHeight: 'relaxed',
        spacing: { top: 1, bottom: 6 },
      },
      {
        id: crypto.randomUUID(),
        type: 'subheading',
        text: 'How You Can Help',
        size: 'xl',
        align: 'left',
        weight: 600,
        spacing: { top: 7, bottom: 4 },
      },
      {
        id: crypto.randomUUID(),
        type: 'text',
        text: 'If you know anyone at mid-market SaaS companies looking to solve workflow automation, I\'d love an introduction.',
        size: 'base',
        align: 'left',
        lineHeight: 'relaxed',
        spacing: { top: 1, bottom: 7 },
      },
      {
        id: crypto.randomUUID(),
        type: 'divider',
        thickness: 1,
        spacing: { top: 7, bottom: 7 },
      },
      {
        id: crypto.randomUUID(),
        type: 'text',
        text: 'Thank you for your continued support.\n\n— Your Name\nFounder & CEO',
        size: 'sm',
        align: 'left',
        lineHeight: 'relaxed',
        spacing: { top: 1, bottom: 1 },
      },
    ],
  },
  {
    id: 'investor-outreach',
    name: 'Investor Outreach',
    description: 'First contact with investors. Clean, credible, compelling.',
    category: 'outreach',
    sections: [
      {
        id: crypto.randomUUID(),
        type: 'heading',
        text: 'Building the Future of Workflow Automation',
        size: '2xl',
        align: 'left',
        weight: 600,
        spacing: { top: 1, bottom: 5 },
      },
      {
        id: crypto.randomUUID(),
        type: 'text',
        text: 'Hi [Name],',
        size: 'base',
        align: 'left',
        lineHeight: 'relaxed',
        spacing: { top: 6, bottom: 4 },
      },
      {
        id: crypto.randomUUID(),
        type: 'text',
        text: 'I\'m reaching out because we\'re building something that aligns with your thesis on vertical SaaS. We\'ve created a workflow automation platform specifically for mid-market operations teams, and we\'re seeing extraordinary traction.',
        size: 'base',
        align: 'left',
        lineHeight: 'relaxed',
        spacing: { top: 1, bottom: 5 },
      },
      {
        id: crypto.randomUUID(),
        type: 'subheading',
        text: 'What We\'ve Built',
        size: 'lg',
        align: 'left',
        weight: 600,
        spacing: { top: 6, bottom: 3 },
      },
      {
        id: crypto.randomUUID(),
        type: 'text',
        text: 'A no-code automation platform that connects legacy systems with modern tools. Our customers reduce manual work by 60% in their first month.',
        size: 'base',
        align: 'left',
        lineHeight: 'relaxed',
        spacing: { top: 1, bottom: 5 },
      },
      {
        id: crypto.randomUUID(),
        type: 'subheading',
        text: 'Traction',
        size: 'lg',
        align: 'left',
        weight: 600,
        spacing: { top: 6, bottom: 3 },
      },
      {
        id: crypto.randomUUID(),
        type: 'text',
        text: '$127K MRR with 89 customers\n40% month-over-month growth\nFirst Fortune 500 customer signed\n8-month CAC payback',
        size: 'base',
        align: 'left',
        lineHeight: 'loose',
        spacing: { top: 1, bottom: 6 },
      },
      {
        id: crypto.randomUUID(),
        type: 'text',
        text: 'We\'re raising a $3M seed round to scale our go-to-market. Would you be open to a 20-minute conversation?',
        size: 'base',
        align: 'left',
        lineHeight: 'relaxed',
        spacing: { top: 6, bottom: 5 },
      },
      {
        id: crypto.randomUUID(),
        type: 'button',
        text: 'Schedule a Call',
        align: 'left',
        style: 'solid',
        spacing: { top: 5, bottom: 7 },
      },
      {
        id: crypto.randomUUID(),
        type: 'text',
        text: 'Best,\n— Your Name',
        size: 'sm',
        align: 'left',
        lineHeight: 'relaxed',
        spacing: { top: 1, bottom: 1 },
      },
    ],
  },
  {
    id: 'product-launch',
    name: 'Product Launch',
    description: 'Announce a new product or feature. Cinematic and compelling.',
    category: 'product',
    sections: [
      {
        id: crypto.randomUUID(),
        type: 'heading',
        text: 'Introducing Enterprise Workflows',
        size: '4xl',
        align: 'center',
        weight: 600,
        spacing: { top: 8, bottom: 4 },
      },
      {
        id: crypto.randomUUID(),
        type: 'text',
        text: 'A new way to automate at scale.',
        size: 'lg',
        align: 'center',
        lineHeight: 'relaxed',
        spacing: { top: 1, bottom: 8 },
      },
      {
        id: crypto.randomUUID(),
        type: 'divider',
        thickness: 1,
        spacing: { top: 7, bottom: 7 },
      },
      {
        id: crypto.randomUUID(),
        type: 'subheading',
        text: 'Built for Teams That Move Fast',
        size: 'xl',
        align: 'left',
        weight: 600,
        spacing: { top: 6, bottom: 4 },
      },
      {
        id: crypto.randomUUID(),
        type: 'text',
        text: 'After months of working with our enterprise customers, we learned what they really needed: workflows that scale across hundreds of users without breaking. Today, we\'re launching Enterprise Workflows — a system designed for reliability, security, and speed.',
        size: 'base',
        align: 'left',
        lineHeight: 'relaxed',
        spacing: { top: 1, bottom: 6 },
      },
      {
        id: crypto.randomUUID(),
        type: 'subheading',
        text: 'What\'s New',
        size: 'xl',
        align: 'left',
        weight: 600,
        spacing: { top: 7, bottom: 4 },
      },
      {
        id: crypto.randomUUID(),
        type: 'text',
        text: 'Advanced permissions and role management\nAudit logs for compliance\nSSO and SAML support\n99.9% uptime SLA\nDedicated account management',
        size: 'base',
        align: 'left',
        lineHeight: 'loose',
        spacing: { top: 1, bottom: 7 },
      },
      {
        id: crypto.randomUUID(),
        type: 'button',
        text: 'Learn More',
        align: 'center',
        style: 'solid',
        spacing: { top: 6, bottom: 6 },
      },
    ],
  },
  {
    id: 'feature-update',
    name: 'Feature Update',
    description: 'Quick update about a new feature. Clean and focused.',
    category: 'update',
    sections: [
      {
        id: crypto.randomUUID(),
        type: 'heading',
        text: 'New: Real-Time Collaboration',
        size: '2xl',
        align: 'left',
        weight: 600,
        spacing: { top: 1, bottom: 5 },
      },
      {
        id: crypto.randomUUID(),
        type: 'text',
        text: 'You can now work on workflows with your team in real time. See changes instantly, avoid conflicts, and ship faster.',
        size: 'base',
        align: 'left',
        lineHeight: 'relaxed',
        spacing: { top: 1, bottom: 6 },
      },
      {
        id: crypto.randomUUID(),
        type: 'subheading',
        text: 'How It Works',
        size: 'lg',
        align: 'left',
        weight: 600,
        spacing: { top: 6, bottom: 3 },
      },
      {
        id: crypto.randomUUID(),
        type: 'text',
        text: 'Open any workflow and invite teammates. You\'ll see their cursors, edits, and comments in real time. No more version conflicts or lost work.',
        size: 'base',
        align: 'left',
        lineHeight: 'relaxed',
        spacing: { top: 1, bottom: 6 },
      },
      {
        id: crypto.randomUUID(),
        type: 'button',
        text: 'Try It Now',
        align: 'left',
        style: 'solid',
        spacing: { top: 5, bottom: 1 },
      },
    ],
  },
  {
    id: 'feedback-request',
    name: 'Feedback Request',
    description: 'Simple, respectful ask for user feedback.',
    category: 'outreach',
    sections: [
      {
        id: crypto.randomUUID(),
        type: 'heading',
        text: 'We\'d Love Your Feedback',
        size: '2xl',
        align: 'left',
        weight: 600,
        spacing: { top: 1, bottom: 5 },
      },
      {
        id: crypto.randomUUID(),
        type: 'text',
        text: 'Hi [Name],',
        size: 'base',
        align: 'left',
        lineHeight: 'relaxed',
        spacing: { top: 1, bottom: 4 },
      },
      {
        id: crypto.randomUUID(),
        type: 'text',
        text: 'You\'ve been using our platform for three months now, and we\'d love to hear how it\'s working for you.',
        size: 'base',
        align: 'left',
        lineHeight: 'relaxed',
        spacing: { top: 1, bottom: 5 },
      },
      {
        id: crypto.randomUUID(),
        type: 'text',
        text: 'Would you have 15 minutes for a quick call? Your insights directly shape what we build next.',
        size: 'base',
        align: 'left',
        lineHeight: 'relaxed',
        spacing: { top: 1, bottom: 6 },
      },
      {
        id: crypto.randomUUID(),
        type: 'button',
        text: 'Schedule 15 Minutes',
        align: 'left',
        style: 'solid',
        spacing: { top: 5, bottom: 7 },
      },
      {
        id: crypto.randomUUID(),
        type: 'text',
        text: 'Thank you,\n— Your Name',
        size: 'sm',
        align: 'left',
        lineHeight: 'relaxed',
        spacing: { top: 1, bottom: 1 },
      },
    ],
  },
  {
    id: 'blank',
    name: 'Blank Canvas',
    description: 'Start from nothing. Pure creative freedom.',
    category: 'founder',
    sections: [],
  },
];

export function createTemplateFromPreset(preset: TemplatePreset): EmailTemplate {
  return {
    id: crypto.randomUUID(),
    name: preset.name,
    sections: preset.sections.map((section) => ({
      ...section,
      id: crypto.randomUUID(),
    })),
    meta: {
      created: new Date().toISOString(),
      modified: new Date().toISOString(),
    },
    settings: {
      width: 600,
      paddingX: 6,
      paddingY: 8,
    },
  };
}
